# Generated by Django 4.0.3 on 2022-03-05 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=music.models.get_album_image_path)),
                ('description', models.TextField()),
                ('release_at', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('AL', 'Album'), ('SG', 'Single'), ('DS', 'DigitalSingle'), ('MN', 'Mini'), ('RP', 'Repackage'), ('SA', 'SpecialAddition'), ('BL', 'Bootleg'), ('CO', 'Compilation')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=300)),
                ('is_title', models.BooleanField(default=False)),
                ('lyrics', models.TextField()),
                ('description', models.TextField()),
                ('duration', models.TimeField()),
                ('released_date', models.DateField()),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('genre', models.ManyToManyField(to='genre.genre')),
            ],
        ),
    ]
