# Generated by Django 4.0.3 on 2022-03-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_delete_artistalbum'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='featuring',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', through='music.ArtistAlbum', to='artist.artist'),
        ),
        migrations.AddField(
            model_name='artistalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.album'),
        ),
        migrations.AddField(
            model_name='artistalbum',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artist.artist'),
        ),
    ]
