# Generated by Django 4.0.3 on 2022-03-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_delete_artistalbum'),
        ('music', '0002_artistalbum_rename_artist_song_featuring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(related_name='albums', through='music.ArtistAlbum', to='artist.artist'),
        ),
    ]
