# Generated by Django 4.0.3 on 2022-03-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_artists_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artists',
        ),
    ]
