# Generated by Django 4.0.3 on 2022-03-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_delete_artistalbum'),
        ('music', '0004_rename_artist_album_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='albums', through='music.ArtistAlbum', to='artist.artist'),
        ),
    ]
