# Generated by Django 4.0.3 on 2022-03-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='featuring',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
