# Generated by Django 4.0.3 on 2022-03-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_delete_artistalbum'),
        ('music', '0006_alter_song_featuring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, through='music.ArtistAlbum', to='artist.artist'),
        ),
    ]
