# Generated by Django 4.0.3 on 2022-03-30 10:37

import artist.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('debut_date', models.DateField(default=datetime.datetime.now)),
                ('is_disbanded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=artist.models.get_artist_profile_image_path)),
                ('stage_name', models.CharField(max_length=150)),
                ('real_name', models.CharField(max_length=150)),
                ('birthday', models.DateField(default=datetime.datetime.now)),
                ('agency', models.CharField(blank=True, max_length=150, null=True)),
                ('introduction', models.TextField()),
                ('career', models.TextField(default='없음')),
                ('debut_date', models.DateField(blank=True, null=True)),
                ('group', models.ManyToManyField(blank=True, to='artist.group')),
            ],
        ),
    ]
