# Generated by Django 4.0.3 on 2022-03-03 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=150)),
                ('real_name', models.CharField(max_length=150)),
                ('birthday', models.DateField(default=datetime.datetime.now)),
                ('agency', models.CharField(blank=True, max_length=150, null=True)),
                ('introduction', models.TextField()),
                ('career', models.TextField(default='없음')),
                ('debut_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('debut_date', models.DateField(default=datetime.datetime.now)),
                ('is_disbanded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artist.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='group',
            field=models.ManyToManyField(blank=True, to='artist.group'),
        ),
    ]
