# Generated by Django 4.0.3 on 2022-03-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistAlbum',
        ),
    ]
