# Generated by Django 4.0.3 on 2022-03-12 16:29

import artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_delete_artistalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=artist.models.get_artist_profile_image_path),
        ),
    ]
