# Generated by Django 4.0.3 on 2022-03-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_playlists',
            field=models.ManyToManyField(blank=True, related_name='users_like', to='playlist.playlist'),
        ),
        migrations.DeleteModel(
            name='PlayList',
        ),
    ]
