# Generated by Django 4.0.3 on 2022-03-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Relationship',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='folowing',
            new_name='following',
        ),
    ]
