# Generated by Django 4.0.3 on 2022-03-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_playlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='relationships',
            new_name='followers',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlists', to='user.user'),
        ),
    ]
