# Generated by Django 4.0.3 on 2022-03-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
        ('music', '0001_initial'),
        ('user', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='like_genres',
            new_name='favorite_genres',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_musics',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_playlists',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_musics',
            field=models.ManyToManyField(blank=True, related_name='users_favorite', to='music.song'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_playlists',
            field=models.ManyToManyField(blank=True, related_name='users_favorite', to='playlist.playlist'),
        ),
    ]
